version: '3.8'
services:
  madadiuk-app:
    build:
      context: .
      dockerfile: madadiuk.dockerfile
    container_name: madadiuk-app
    tty: true
    environment:
      SERVICE_NAME: madadiuk-app
      SERVICE_TAGS: dev
    working_dir: /var/www/server
    volumes:
      - ./app:/var/www/server
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - madadiuk-network
    depends_on:
      - madadiuk-mysql
    command: /bin/bash -c "php-fpm | /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"

  madadiuk-web:
    build:
      context: ./
      dockerfile: madadiuk-webserver.dockerfile
    container_name: madadiuk-web
    tty: true
    ports:
      - "8087:80"
    volumes:
      - ./app:/var/www/server
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - madadiuk-app
    networks:
      - madadiuk-network

  madadiuk-mysql:
    image: mysql:8.0
    container_name: madadiuk-mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - madadiuk-network

networks:
  madadiuk-network:
    driver: bridge

volumes:
  db_data:
    driver: local
